#define BSEXPR_OP_AND                          1
#define BSEXPR_OP_OR                           2
#define BSEXPR_OP_EQ                           3
#define BSEXPR_OP_NE                           4
#define BSEXPR_OP_LT                           5
#define BSEXPR_OP_LE                           6
#define BSEXPR_OP_GT                           7
#define BSEXPR_OP_GE                           8
#define BSEXPR_OP_ADD                          9
#define BSEXPR_OP_SUB                         10
#define BSEXPR_OP_MULT                        11
#define BSEXPR_OP_DIV                         12
#define BSEXPR_OP_MOD                         13
#define BSEXPR_OP_NOT                         14
#define BSEXPR_OP_NEG                         15
#define BSEXPR_L_LPAREN                       16
#define BSEXPR_L_RPAREN                       17
#define BSEXPR_L_STRING                       18
#define BSEXPR_L_FLOAT                        19
#define BSEXPR_L_INT                          20
#define BSEXPR_L_VAR                          21
#define BSEXPR_L_PROC                         22
#define BSEXPR_L_FUNC                         23
#define BSEXPR_L_COMMA                        24
