BASE=../cs/home/ivy
TXM=txm

include ${BASE}/ve-2.2/autocfg.mk
include ${BASE}/ve-2.2/Make.config

INCDIR=${BASE}/ve-2.2/include
LIBDIR=${BASE}/ve-2.2/lib
OPENGL=${ACFG_OPENGL}

CFLAGS+= -I${INCDIR}

OBJS=	loadTexture.o 3ds.o 3dsRenderer.o 


3dslib: ${OBJS} 
	ar r linux/lib3ds.a ${OBJS}
	ranlib linux/lib3ds.a

clean:
	rm -f ${OBJS} linux/lib3ds.a





