BASE=${HOME}/VR_Projects/cs/home/ivy
TXM=txm

include ${BASE}/ve-2.2/autocfg.mk
include ${BASE}/ve-2.2/Make.config

INCDIR=${BASE}/ve-2.2/include
LIBDIR=${BASE}/ve-2.2/lib 
OPENGL=${ACFG_OPENGL}

CFLAGS+= -I${INCDIR} -I../3ds -I../vem
LDFLAGS= ${CFLAGS} -L${LIBDIR} -lve -L../3ds/linux -l3ds -L../vem/linux -lvem

OBJS=	play2.o 


play2 : ${OBJS} 
	$(CC) ${OBJS} $(LDFLAGS) -o play2.linux ${LIBPATH}  ${OPENGL} 
${OSLIBS}


play2 : play2.o
	$(CC) play2.o $(LDFLAGS) -o play2.linux ${LIBPATH}  ${OPENGL} ${OSLIBS} 

