BASE=../cs/home/ivy
TXM=txm

include ${BASE}/ve-2.2/autocfg.mk
include ${BASE}/ve-2.2/Make.config

INCDIR=${BASE}/ve-2.2/include
LIBDIR=${BASE}/ve-2.2/lib 
OPENGL=${ACFG_OPENGL}

CFLAGS+= -I${INCDIR} -I../3ds -I../vem
LDFLAGS= ${CFLAGS} -L${LIBDIR} -lve -L../3ds/linux -l3ds -L../vem/linux -lvem

OBJS=	3dsviewer.o 


3dsviewer : ${OBJS} 
	$(CC) ${OBJS} $(LDFLAGS) -o 3dsviewer.linux ${LIBPATH}  ${OPENGL} ${OSLIBS}



